name: Build and Release Docs to Github Pages

on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx~=2.4.4 m2r numpydoc --upgrade

          # install numpyro from git bc the pypi release is too strict about jax
          pip install git+https://github.com/pyro-ppl/numpyro
          python setup.py develop

      - name: Build docs
        run: sphinx-build docs build
        env:
          SPHINX_BUILD_PROD: true

      - name: Deploy docs to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./build
