name: Main Workflow

on: push

jobs:
  build:
    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip

          # test deps
          pip install --upgrade black pytest pytest-cov codecov

          # install deps manually bc pypi numpyro is too strict.
          pip install --upgrade jax jaxlib numpyro tqdm pandas
          pip install git+https://github.com/pyro-ppl/numpyro --no-deps
          python setup.py develop --no-deps

      - name: Lint with Black
        run: black . --check --verbose

      - name: Run unit tests with Pytest
        run: pytest --verbose --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          name: ${{matrix.python-version}}
          file: ./coverage.xml
