name: Scheduled Testing

on:
  schedule:
    - cron: "0 0 * * 5" # run scheduled tests every friday, in time to ruin my weekend.

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip

          # test deps
          pip install --upgrade pytest

          # install deps manually bc pypi numpyro is too strict.
          pip install --upgrade jax jaxlib numpyro tqdm pandas
          pip install git+https://github.com/pyro-ppl/numpyro --no-deps
          python setup.py develop --no-deps

      - name: Run unit tests with Pytest
        run: pytest --verbose
